# YBFuzz Configuration File
# World-class Staff SDET database fuzzer configuration

# Database Configuration
database:
  host: "10.9.86.186,10.9.139.177,10.9.205.248"
  port: 5433
  user: "yugabyte"
  password: "Password#123"
  database: "yugabyte"
  schema_name: "ybfuzz_schema"
  connection_timeout: 30
  max_connections: 10

# Fuzzing Configuration
fuzzing:
  duration: 300  # 5 minutes default
  max_sessions: 100
  queries_per_session: 10
  mutation_rate: 0.3
  seed_corpus_size: 100
  evolved_corpus_size: 50
  
  # Advanced fuzzing strategies
  strategies:
    grammar_based: true
    mutation_based: true
    corpus_based: true
    feedback_driven: true
    adaptive_mutation: true

# Oracle Configuration - Advanced Bug Detection
oracles:
  # Core Oracles (Always Enabled)
  tlp:
    enabled: true
    max_partitions: 3
    enable_advanced_partitioning: true
    
  qpg:
    enabled: true
    plan_observation_threshold: 10
    mutation_strategies: ["table_state", "index_state", "data_state"]
    
  # Advanced Oracles (Configurable)
  pqs:
    enabled: false  # Enable for Pivoted Query Synthesis
    max_pivot_attempts: 10
    min_pivot_rows: 5
    enable_cross_table_pivoting: true
    
  norec:
    enabled: false  # Enable for Non-optimizing Reference Engine Construction
    enable_hints: true
    max_rewrite_attempts: 5
    optimization_strategies: ["hint_based", "rewrite_based", "redundant_conditions"]
    
  cert:
    enabled: false  # Enable for Cardinality Estimation Restriction Testing
    enable_explain: true
    max_restriction_attempts: 3
    cardinality_threshold: 0.1
    performance_analysis: true
    
  dqp:
    enabled: false  # Enable for Differential Query Plans
    enable_plan_control: true
    max_plan_variations: 3
    plan_hints: ["index_hints", "join_hints", "optimization_hints"]
    
  coddtest:
    enabled: false  # Enable for Constant Optimization Driven Testing
    enable_constant_folding: true
    enable_constant_propagation: true
    max_substitution_attempts: 5
    optimization_levels: ["basic", "intermediate", "advanced"]

# Query Generation Configuration
generation:
  # Grammar-based generation
  grammar_file: "core/grammar.yaml"
  max_recursion_depth: 5
  max_query_length: 1000
  
  # Advanced generation strategies
  strategies:
    context_aware: true
    schema_aware: true
    type_aware: true
    constraint_aware: true
    
  # Query complexity control
  complexity:
    max_joins: 3
    max_subqueries: 2
    max_aggregations: 2
    max_window_functions: 1

# Mutation Configuration
mutation:
  # Mutation strategies
  strategies:
    - "column_substitution"
    - "operator_mutation"
    - "clause_reordering"
    - "type_conversion"
    - "null_handling"
    - "edge_case_injection"
    
  # Mutation parameters
  parameters:
    mutation_rate: 0.3
    max_mutations_per_query: 3
    preserve_semantics: true
    
  # Advanced mutation techniques
  advanced:
    semantic_preservation: true
    constraint_aware_mutation: true
    feedback_driven_mutation: true

# Bug Reporting Configuration
bug_reporting:
  # Report organization
  organize_by:
    - "bug_type"
    - "oracle"
    - "severity"
    - "category"
    
  # Report formats
  formats:
    - "json"
    - "sql"
    - "markdown"
    - "html"
    
  # Report content
  content:
    include_reproduction: true
    include_context: true
    include_statistics: true
    include_metadata: true
    
  # Advanced reporting
  advanced:
    bug_clustering: true
    duplicate_detection: true
    severity_classification: true
    impact_analysis: true

# Performance Configuration
performance:
  # Query execution
  execution:
    timeout: 30
    max_memory: "1GB"
    parallel_execution: true
    connection_pooling: true
    
  # Optimization
  optimization:
    query_planning: true
    result_caching: true
    adaptive_execution: true
    
  # Monitoring
  monitoring:
    performance_metrics: true
    resource_usage: true
    bottleneck_detection: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - [%(name)s] - %(message)s"
  
  # Log destinations
  destinations:
    - "console"
    - "file"
    - "syslog"
    
  # Advanced logging
  advanced:
    structured_logging: true
    log_rotation: true
    log_compression: true
    performance_logging: true

# Security Configuration
security:
  # Input validation
  validation:
    sql_injection_protection: true
    query_sanitization: true
    parameter_validation: true
    
  # Access control
  access_control:
    user_privileges: true
    schema_isolation: true
    query_restrictions: true

# Testing Configuration
testing:
  # Test modes
  modes:
    smoke_test: false
    regression_test: false
    performance_test: false
    stress_test: false
    
  # Test coverage
  coverage:
    statement_coverage: true
    branch_coverage: true
    oracle_coverage: true
    
  # Test validation
  validation:
    result_verification: true
    performance_baseline: true
    regression_detection: true

# Advanced Features
advanced:
  # Machine Learning Integration
  ml_integration:
    enabled: false
    model_path: "models/"
    training_data: "data/training/"
    
  # AI-Powered Generation
  ai_generation:
    enabled: false
    model_type: "transformer"
    context_window: 1024
    
  # Distributed Fuzzing
  distributed:
    enabled: false
    worker_nodes: 4
    coordination: "redis"
    
  # Real-time Analysis
  real_time:
    enabled: false
    streaming: true
    alerting: true
