# ==========================================================
# YBFuzz Framework Configuration
# ==========================================================

# --- Run Control ---
duration: 300
max_sessions: 500 # We now think in terms of sessions, not queries
random_seed: null
log_level: INFO
log_file: "ybfuzz_run.log"
bug_report_file: "bugs.log"
sql_log_file: "executed_queries.sql"
catalog_refresh_interval: 5 # Refresh more often in stateful mode

# --- Database Connection ---
database:
  host: "127.0.0.1"
  port: 5433
  user: "yugabyte"
  password: "yugabyte"
  dbname: "yugabyte"
  schema_name: "ybfuzz_schema"

# --- Initial Database State ---
initial_db_setup_sqls:
  - "CREATE TABLE $$schema$$.products (id INT PRIMARY KEY, name TEXT, category TEXT, price NUMERIC, stock_count INT);"
  - "INSERT INTO $$schema$$.products SELECT g, 'Product-' || g, 'Category-' || (g%10), g*1.5, g*10 FROM generate_series(1,100) g;"
  - "CREATE TABLE $$schema$$.orders (order_id INT PRIMARY KEY, product_id INT, quantity INT, order_date DATE);"
  - "INSERT INTO $$schema$$.orders SELECT g, 1 + (g%100), 1 + (g%5), '2025-01-01'::date + (g || ' days')::interval FROM generate_series(1, 200) g;"

# --- Fuzzer Engine Strategy ---
engine_strategy:
  mutation_probability: 0.7

# --- Corpus for Mutational Engine ---
corpus:
  seed_file: "corpus/seed_queries.txt"

# --- Grammar File for Generative Engine ---
grammar_file: "core/grammar.yaml"

# --- NEW: Stateful Session Strategy ---
# Defines the "shape" of each test case. The engine will generate and execute
# statements in this order before validating the final SELECT.
session_strategy:
  # Generate between 1 and 2 DDL statements (CREATE TABLE, VIEW, INDEX)
  ddl_statements: [1, 2]
  # Generate between 3 and 8 DML statements (INSERT, UPDATE, DELETE)
  dml_statements: [3, 8]
  # Always finish with 1 SELECT statement, which is passed to the oracles
  final_select_statements: 1

# --- Grammar and Generator Control ---
max_recursion_depth:
  expression: 5

# Weights for choosing which statement to generate within a phase
statement_weights:
  ddl_statement:
    create_table_stmt: 50
    create_view_stmt: 30
    create_index_stmt: 20
  dml_statement:
    insert_stmt: 50
    update_stmt: 40
    delete_stmt: 10
  select_stmt: 100 # Only one option for the final select

rule_choice_weights:
  select_list_item:
    column_name: 0.5
    aggregate_function: 0.4
    scalar_function: 0.1

rule_expansion_probabilities:
  select_stmt:
    WHERE: 0.9
    GROUP_BY: 0.7
    LIMIT: 0.4
  boolean_term:
    AND: 0.5

# --- Oracle Configuration ---
oracles:
  TLOracle:
    enabled: true
    enable_norec: true
    enable_tlp: true
    norec_settings:
      - "enable_nestloop"
      - "enable_hashjoin"
  
  QPGOracle:
    enabled: true
    enable_cert: true
    enable_dqp: true
    enable_coddtest: true
    cert_threshold: 100
